### ISSUE TITLE
廖老师，能不能支持其他端登录。。。微博没有账号也没有手机。。。

### ISSUE THREAD

**Issue by Hacker-070404** [michaelliao/itranswarp#21]

**Comment by michaelliao** [comment]
你想用啥登录？

**Comment by Hacker-070404** [comment]
可以用QQ,邮箱，Github也可以。。。毕竟没有手机。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Michael Liao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月9日(星期一) 下午4:22
收件人:&nbsp;"michaelliao/itranswarp"<itranswarp@noreply.github.com&gt;;
抄送:&nbsp;"Shining Stars"<1612425701@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [michaelliao/itranswarp] 廖老师，能不能支持其他端登录。。。微博没有账号也没有手机。。。 (#21)




你想用啥登录？

**Comment by michaelliao** [comment]
找到application.yml:

```
...
  signin:
    oauth:
      github:
        client-id: xxx
        client-secret: xxx
```
